// src/lib/projects.ts

export type Project = {
  id: number;
  category: "flyer" | "thumbnail" | "banner" | "web" | "illust" | "movie" ;
  title: string;
  image: string;
  description?: string;
  time?: string;
  link?: string;
};

export const projects: Project[] = [


{id: 1, category: 'thumbnail', title: 'ゆったりカフェBGM【その1】', image: '/images/thumb_00001.jpg', time: '約1時間', link: ''},
{id: 2, category: 'thumbnail', title: 'ゆったりカフェBGM【その2】', image: '/images/thumb_00002.jpg', time: '約1時間', link: ''},
{id: 3, category: 'thumbnail', title: '雑学としての半導体', image: '/images/thumb_00003.jpg', time: '約1時間', link: ''},
{id: 4, category: 'thumbnail', title: '仕事のデジタル化・効率化', image: '/images/thumb_00004.jpg', time: '約1時間', link: ''},
{id: 5, category: 'thumbnail', title: '医師がすすめる最高の朝食', image: '/images/thumb_00005.jpg', time: '約1.5時間', link: ''},
{id: 6, category: 'thumbnail', title: '女性が綺麗に見える体重', image: '/images/thumb_00006.jpg', time: '約2時間', link: ''},
{id: 7, category: 'thumbnail', title: 'プログラマーの必須知識', image: '/images/thumb_00007.jpg', time: '約1時間', link: ''},
{id: 8, category: 'thumbnail', title: '在宅で月10万稼ぐ', image: '/images/thumb_00008.jpg', time: '約1時間', link: ''},
{id: 9, category: 'thumbnail', title: 'ご当地グルメ大集合【その1】', image: '/images/thumb_00009.jpg', time: '約1.5時間', link: ''},
{id: 10, category: 'thumbnail', title: 'ご当地グルメ大集合【その2】', image: '/images/thumb_00010.jpg', time: '約1.5時間', link: ''},
{id: 11, category: 'thumbnail', title: '空間浄化', image: '/images/thumb_00011.jpg', time: '約2.5時間', link: ''},
{id: 12, category: 'thumbnail', title: '沖縄音楽【その1】', image: '/images/thumb_00012.jpg', time: '約1時間', link: ''},
{id: 13, category: 'thumbnail', title: '沖縄音楽【その2】', image: '/images/thumb_00013.jpg', time: '約1.5時間', link: ''},
{id: 14, category: 'thumbnail', title: '雑学まとめ25選【その1】', image: '/images/thumb_00014.jpg', time: '約2時間', link: ''},
{id: 15, category: 'thumbnail', title: '雑学まとめ25選【その2】', image: '/images/thumb_00015.jpg', time: '約2時間', link: ''},
{id: 16, category: 'thumbnail', title: '中年の人生戦略【その1】', image: '/images/thumb_00016.jpg', time: '約1時間', link: ''},
{id: 17, category: 'thumbnail', title: '中年の人生戦略【その2】', image: '/images/thumb_00017.jpg', time: '約1.5時間', link: ''},
{id: 18, category: 'thumbnail', title: '環境が行動を決める', image: '/images/thumb_00018.jpg', time: '約1時間', link: ''},
{id: 19, category: 'thumbnail', title: '肌をキレイにするために始めたこと', image: '/images/thumb_00019.jpg', time: '約1.5時間', link: ''},
{id: 20, category: 'thumbnail', title: '未経験からエンジニアになった方法', image: '/images/thumb_00020.jpg', time: '約1時間', link: ''},
{id: 21, category: 'thumbnail', title: '差がつく話し方', image: '/images/thumb_00021.jpg', time: '約1時間', link: ''},
{id: 22, category: 'thumbnail', title: 'うますぎるペペロンチーノ', image: '/images/thumb_00022.jpg', time: '約1時間', link: ''},
{id: 23, category: 'thumbnail', title: '波動を知れば引き寄せは簡単', image: '/images/thumb_00023.jpg', time: '約1時間', link: ''},
{id: 24, category: 'thumbnail', title: '洋楽PLAYLIST', image: '/images/thumb_00024.jpg', time: '約1時間', link: ''},
{id: 25, category: 'thumbnail', title: '頭の回転を3倍にする習慣', image: '/images/thumb_00025.jpg', time: '約1時間', link: ''},
{id: 26, category: 'thumbnail', title: '利益を上げる考え方', image: '/images/thumb_00026.jpg', time: '約1時間', link: ''},
{id: 27, category: 'thumbnail', title: '体力がある人ない人', image: '/images/thumb_00027.jpg', time: '約1時間', link: ''},
{id: 28, category: 'thumbnail', title: '0円美容法', image: '/images/thumb_00028.jpg', time: '約1時間', link: ''},
{id: 29, category: 'thumbnail', title: 'プログラム自動化', image: '/images/thumb_00029.jpg', time: '約1.5時間', link: ''},
{id: 30, category: 'thumbnail', title: '習慣10選', image: '/images/thumb_00030.jpg', time: '約1時間', link: ''},
{id: 31, category: 'thumbnail', title: 'ばあちゃんに教わったぬか漬け', image: '/images/thumb_00031.jpg', time: '約1時間', link: ''},
{id: 32, category: 'thumbnail', title: '行動する前に知っておいてほしいこと', image: '/images/thumb_00032.jpg', time: '約1.5時間', link: ''},
{id: 33, category: 'thumbnail', title: '静かなJAZZ音楽【その1】', image: '/images/thumb_00033.jpg', time: '約1時間', link: ''},
{id: 34, category: 'thumbnail', title: '静かなJAZZ音楽【その2】', image: '/images/thumb_00034.jpg', time: '約1.5時間', link: ''},
{id: 35, category: 'thumbnail', title: '人生の時間倍になる', image: '/images/thumb_00035.jpg', time: '約2時間', link: ''},
{id: 36, category: 'thumbnail', title: '最強のマネープラン', image: '/images/thumb_00036.jpg', time: '約1時間', link: ''},
{id: 37, category: 'thumbnail', title: 'コーヒーの凄すぎる効果', image: '/images/thumb_00037.jpg', time: '約1時間', link: ''},
{id: 38, category: 'thumbnail', title: '絶対に選ぶ保湿クリーム', image: '/images/thumb_00038.jpg', time: '約1時間', link: ''},
{id: 39, category: 'thumbnail', title: 'インターネット原理と仕組み', image: '/images/thumb_00039.jpg', time: '約1時間', link: ''},
{id: 40, category: 'thumbnail', title: '基本の肉じゃが', image: '/images/thumb_00040.jpg', time: '約1時間', link: ''},
{id: 41, category: 'thumbnail', title: '心が美しい人の特徴', image: '/images/thumb_00041.jpg', time: '約1.5時間', link: ''},
{id: 42, category: 'thumbnail', title: '恋愛の悩み終わります', image: '/images/thumb_00042.jpg', time: '約1時間', link: ''},
{id: 43, category: 'thumbnail', title: '大金運を引き寄せる動画', image: '/images/thumb_00043.jpg', time: '約2.5時間', link: ''},
{id: 44, category: 'thumbnail', title: '見ればすべて終わる', image: '/images/thumb_00044.jpg', time: '約2.5時間', link: ''},
{id: 45, category: 'banner', title: '出張撮影', image: '/images/banner_00001.jpg', time: '約1.5時間', link: ''},
{id: 46, category: 'banner', title: 'アフィリエイトで稼ぐノウハウ', image: '/images/banner_00002.jpg', time: '約2時間', link: ''},
{id: 47, category: 'banner', title: '犬服ハンドメイド', image: '/images/banner_00003.jpg', time: '約1.5時間', link: ''},
{id: 48, category: 'banner', title: '中学受験 算数', image: '/images/banner_00004.jpg', time: '約2時間', link: ''},
{id: 49, category: 'banner', title: '片思いの恋愛相談', image: '/images/banner_00005.jpg', time: '約3時間', link: ''},
{id: 50, category: 'banner', title: 'オンラインダンスレッスン', image: '/images/banner_00006.jpg', time: '約3時間', link: ''},
{id: 51, category: 'banner', title: '美しく痩せる', image: '/images/banner_00007.jpg', time: '約2時間', link: ''},
{id: 52, category: 'banner', title: 'タロット鑑定', image: '/images/banner_00008.jpg', time: '約3時間', link: ''},
{id: 53, category: 'banner', title: 'AI画像生成プロンプト', image: '/images/banner_00009.jpg', time: '約1.5時間', link: ''},
{id: 54, category: 'banner', title: '好きなことや強みで起業', image: '/images/banner_00010.jpg', time: '約2時間', link: ''},
{id: 55, category: 'banner', title: '翻訳×スピード納品', image: '/images/banner_00011.jpg', time: '約2.5時間', link: ''},
{id: 56, category: 'banner', title: 'C#・VB.NET承ります', image: '/images/banner_00012.jpg', time: '約1.5時間', link: ''},
{id: 57, category: 'banner', title: 'カラオケ音源制作します', image: '/images/banner_00013.jpg', time: '約1.5時間', link: ''},
{id: 58, category: 'banner', title: '確定申告代行', image: '/images/banner_00014.jpg', time: '約2時間', link: ''},
{id: 59, category: 'banner', title: 'SEO対策', image: '/images/banner_00015.jpg', time: '約2時間', link: ''},
{id: 60, category: 'banner', title: '動画編集します', image: '/images/banner_00016.jpg', time: '約1.5時間', link: ''},
{id: 61, category: 'banner', title: 'ホームページ制作', image: '/images/banner_00017.jpg', time: '約2時間', link: ''},
{id: 62, category: 'banner', title: '心をつかむチラシデザイン', image: '/images/banner_00018.jpg', time: '約2.5時間', link: ''},
{id: 63, category: 'banner', title: '漫画の添削します', image: '/images/banner_00019.jpg', time: '約1.5時間', link: ''},
{id: 64, category: 'banner', title: '副業で50万円稼いだノウハウ', image: '/images/banner_00020.jpg', time: '約1.5時間', link: ''},
{id: 65, category: 'banner', title: '着物の出張着付け', image: '/images/banner_00021.jpg', time: '約1.5時間', link: ''},
{id: 66, category: 'banner', title: 'オリジナルTシャツ作成', image: '/images/banner_00022.jpg', time: '約2時間', link: ''},
{id: 67, category: 'banner', title: 'パーソナルボイストレーニング', image: '/images/banner_00023.jpg', time: '約1.5時間', link: ''},
{id: 68, category: 'banner', title: 'ファッションコーディネート7選', image: '/images/banner_00024.jpg', time: '約1.5時間', link: ''},
{id: 69, category: 'banner', title: '模擬面接', image: '/images/banner_00025.jpg', time: '約1.5時間', link: ''},
{id: 70, category: 'banner', title: '心理カウンセラーが話し相手になります', image: '/images/banner_00026.jpg', time: '約1.5時間', link: ''},
{id: 71, category: 'banner', title: '夢鑑定', image: '/images/banner_00027.jpg', time: '約1.5時間', link: ''},
{id: 72, category: 'banner', title: '帳簿作成サポート', image: '/images/banner_00028.jpg', time: '約1.5時間', link: ''},
{id: 73, category: 'banner', title: 'オンライン取材サービス', image: '/images/banner_00029.jpg', time: '約1.5時間', link: ''},
{id: 74, category: 'banner', title: 'Webシステム開発構築', image: '/images/banner_00030.jpg', time: '約1.5時間', link: ''},
{id: 75, category: 'banner', title: 'オリジナルBGM', image: '/images/banner_00031.jpg', time: '約2.5時間', link: ''},
{id: 76, category: 'banner', title: '民泊許認可申請', image: '/images/banner_00032.jpg', time: '約1.5時間', link: ''},
{id: 77, category: 'banner', title: '実践型マーケティング支援', image: '/images/banner_00033.jpg', time: '約1.5時間', link: ''},
{id: 78, category: 'banner', title: '結婚式映像制作', image: '/images/banner_00034.jpg', time: '約2時間', link: ''},
{id: 79, category: 'banner', title: 'HTML・CSS代行', image: '/images/banner_00035.jpg', time: '約1.5時間', link: ''},
{id: 80, category: 'banner', title: '3D-CADで3Dデータ作成', image: '/images/banner_00036.jpg', time: '約1.5時間', link: ''},
{id: 81, category: 'flyer', title: '自動車教習所夏の学割', image: '/images/flyer_00001.jpg', time: '約4時間', link: ''},
{id: 82, category: 'flyer', title: '父の日フェア', image: '/images/flyer_00002.jpg', time: '約4時間', link: ''},
{id: 83, category: 'flyer', title: 'SUMMER HOT Sale', image: '/images/flyer_00003.jpg', time: '約6時間', link: ''},
{id: 84, category: 'flyer', title: 'フィットネスジム', image: '/images/flyer_00004.jpg', time: '約4.5時間', link: ''},
{id: 85, category: 'flyer', title: '浴衣レンタル', image: '/images/flyer_00005.jpg', time: '約4.5時間', link: ''},
{id: 86, category: 'flyer', title: 'お中元セール', image: '/images/flyer_00006.jpg', time: '約4時間', link: ''},
{id: 87, category: 'flyer', title: 'コインランドリー応援セール', image: '/images/flyer_00007.jpg', time: '約5時間', link: ''},
{id: 88, category: 'flyer', title: 'スイーツショップ', image: '/images/flyer_00008.jpg', time: '約4.5時間', link: ''},
{id: 89, category: 'flyer', title: '夏祭り', image: '/images/flyer_00009.jpg', time: '約5.5時間', link: ''},
{id: 90, category: 'flyer', title: '夏休み自由研究', image: '/images/flyer_00010.jpg', time: '約4.5時間', link: ''},
{id: 91, category: 'flyer', title: '楽しく手ぶらでBBQ', image: '/images/flyer_00011.jpg', time: '約4.5時間', link: ''},
{id: 92, category: 'flyer', title: 'Beer Garden【その1】', image: '/images/flyer_00012.jpg', time: '約4時間', link: ''},
{id: 93, category: 'flyer', title: 'Beer Garden【その2】', image: '/images/flyer_00013.jpg', time: '約4時間', link: ''},
{id: 94, category: 'flyer', title: 'SUMMER FESTIVAL【その1】', image: '/images/flyer_00014.jpg', time: '約4時間', link: ''},
{id: 95, category: 'flyer', title: 'SUMMER FESTIVAL【その2】', image: '/images/flyer_00015.jpg', time: '約5時間', link: ''},
{id: 96, category: 'flyer', title: '父の日ゴルフレッスン【その1】', image: '/images/flyer_00016.jpg', time: '約5.5時間', link: ''},
{id: 97, category: 'flyer', title: '父の日ゴルフレッスン【その2】', image: '/images/flyer_00017.jpg', time: '約4.5時間', link: ''},
{id: 98, category: 'flyer', title: 'フルーツ収穫体験【その1】', image: '/images/flyer_00018.jpg', time: '約5時間', link: ''},
{id: 99, category: 'flyer', title: 'フルーツ収穫体験【その2】', image: '/images/flyer_00019.jpg', time: '約4.5時間', link: ''},
{id: 100, category: 'flyer', title: 'SUMMER CAMP【その1】', image: '/images/flyer_00020.jpg', time: '約4.5時間', link: ''},
{id: 101, category: 'flyer', title: 'SUMMER CAMP【その2】', image: '/images/flyer_00021.jpg', time: '約4.5時間', link: ''},
{id: 102, category: 'flyer', title: 'SUMMER CAMP【その3】', image: '/images/flyer_00022.jpg', time: '約5時間', link: ''},
{id: 103, category: 'flyer', title: '成人式【その1】', image: '/images/flyer_00023.jpg', time: '約4時間', link: ''},
{id: 104, category: 'flyer', title: '成人式【その2】', image: '/images/flyer_00024.jpg', time: '約4時間', link: ''},
{id: 105, category: 'flyer', title: 'キャンドルナイト【その1】', image: '/images/flyer_00025.jpg', time: '約4時間', link: ''},
{id: 106, category: 'flyer', title: 'キャンドルナイト【その2】', image: '/images/flyer_00026.jpg', time: '約5時間', link: ''},
{id: 107, category: 'flyer', title: '紅葉めぐり', image: '/images/flyer_00027.jpg', time: '約4時間', link: ''},
{id: 108, category: 'flyer', title: '天体観測会', image: '/images/flyer_00028.jpg', time: '約4時間', link: ''},
{id: 109, category: 'flyer', title: 'Valentine\'s Day', image: '/images/flyer_00029.jpg', time: '約4時間', link: ''},
{id: 110, category: 'flyer', title: '定期演奏会', image: '/images/flyer_00030.jpg', time: '約4.5時間', link: ''},
{id: 111, category: 'flyer', title: 'エステ初体験', image: '/images/flyer_00031.jpg', time: '約4時間', link: ''},
{id: 112, category: 'flyer', title: 'サロンNew Open', image: '/images/flyer_00032.jpg', time: '約4時間', link: ''},
{id: 113, category: 'flyer', title: '私たちの街を再発見', image: '/images/flyer_00033.jpg', time: '約4時間', link: ''},
{id: 114, category: 'flyer', title: 'ランタン作り', image: '/images/flyer_00034.jpg', time: '約4時間', link: ''},
{id: 115, category: 'flyer', title: '保険相談', image: '/images/flyer_00035.jpg', time: '約4時間', link: ''},
{id: 116, category: 'flyer', title: '冬期講習生徒募集', image: '/images/flyer_00036.jpg', time: '約4時間', link: ''},
{id: 117, category: 'flyer', title: '春の住宅大感謝祭', image: '/images/flyer_00037.jpg', time: '約6時間', link: ''},
{id: 118, category: 'flyer', title: '家事代行サービス', image: '/images/flyer_00038.jpg', time: '約6時間', link: ''},
{id: 119, category: 'flyer', title: 'OPEN HOUSE', image: '/images/flyer_00039.jpg', time: '約4時間', link: ''},
{id: 120, category: 'flyer', title: '桜まつり', image: '/images/flyer_00040.jpg', time: '約4.5時間', link: ''},
{id: 121, category: 'flyer', title: 'ベーカリーNEW OPEN', image: '/images/flyer_00041.jpg', time: '約4時間', link: ''},
{id: 122, category: 'flyer', title: '確定申告相談会', image: '/images/flyer_00042.jpg', time: '約4時間', link: ''},
{id: 123, category: 'flyer', title: 'こどもテニスクラブ', image: '/images/flyer_00043.jpg', time: '約5時間', link: ''},
{id: 124, category: 'flyer', title: 'ビストロNew Open', image: '/images/flyer_00044.jpg', time: '約6時間', link: ''},
{id: 125, category: 'flyer', title: '足圧整体院', image: '/images/flyer_00045.jpg', time: '約4時間', link: ''},
{id: 126, category: 'web', title: 'ジュエリースタジオ ノクターン', image: '/images/web_00001.png', time: '約45時間', link: 'https://portfolio.tsukuri-tai.com/a/'},
{id: 127, category: 'illust', title: '車', image: '/images/illust_00001.jpg', time: '約20時間', link: ''},
{id: 128, category: 'illust', title: 'りんご【その1】', image: '/images/illust_00002.jpg', time: '約8時間', link: ''},
{id: 129, category: 'illust', title: '波', image: '/images/illust_00003.jpg', time: '約10時間', link: ''},
{id: 130, category: 'illust', title: 'みかん', image: '/images/illust_00004.jpg', time: '約1.5時間', link: ''},
{id: 131, category: 'illust', title: 'トマト', image: '/images/illust_00005.jpg', time: '約1.5時間', link: ''},
{id: 132, category: 'illust', title: 'たまねぎ', image: '/images/illust_00006.jpg', time: '約1.5時間', link: ''},
{id: 133, category: 'illust', title: 'りんご【その2】', image: '/images/illust_00007.jpg', time: '約2時間', link: ''},
{id: 134, category: 'illust', title: 'ぶどう', image: '/images/illust_00008.jpg', time: '約15時間', link: ''},
{id: 135, category: 'illust', title: 'バナナ', image: '/images/illust_00009.jpg', time: '約15時間', link: ''},
{id: 136, category: 'illust', title: '女性', image: '/images/illust_00010.jpg', time: '約3時間', link: ''},
{id: 137, category: 'movie', title: '3人の同居人', image: '/images/movie_00001.png', time: '約8時間', link: 'https://youtu.be/cGxGXDU0o00?si=jeK62iSeCY7JTTa0'},
{id: 138, category: 'movie', title: 'かんさい三都物語', image: '/images/movie_00002.png', time: '約8時間', link: 'https://youtu.be/mqcTxbF1Ys8?si=r-fDs1w-pN3monFv'},	



];